# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

target 'RemonFull' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleV2
  pod 'RemoteMonster', '2.4.496'

end

target 'RemonCall' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleV2
  pod 'RemoteMonster', '~> 2.0'
#  pod 'Firebase/Core'
#  pod 'Firebase/Database'

end

target 'RemonEx-objc' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for SampleV2
    pod 'RemoteMonster', '~> 2.0'
end

target 'externalSampler' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Pods for SampleV2
    pod 'RemoteMonster', '~> 2.0'
    pod 'GPUImage', '~> 0.1'

end

target 'meshCall' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Pods for SampleV2
    pod 'RemoteMonster', '~> 2.0'
    pod 'GPUImage', '~> 0.1'
end
