# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SimpleRemon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleV2
  pod 'RemoteMonster', '~>2.6.13'

end


target 'SimpleRemonObjC' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for SampleV2
    pod 'RemoteMonster', '~>2.6.13'
end



